name: default_stage3

extractor: "NetworkShallowPool2"
embedder: "GREBilinearPoolPaddingDeepMore"

pretrain: true
pretrain_model_path: "data/model/default_stage2"
pretrain_step: -1
pretrain_extractor: true
pretrain_embedder: true

loss_type: "gefeats"
train_extractor: true
train_embedder: true

batch_size: 2
worker_num: 8

train_step: 10000
warm_up_step: 0
median_step: 5000

save_step: 500
info_step: 50

hem_interval: 8
hem_thresh_begin: 16
hem_thresh_end: 4

lr_warm_up: 0.0001 # 1e-4
lr_begin: 0.0001   # 1e-4
lr_median: 0.00005 # 5e-5
lr_end: 0.00001    # 1e-5

augmentation_args:
    h: 480
    w: 640

    test_harris: true
    harris_percentile: 99
    sample_num: 128

    augment: true
    augment_classes: ["jitter","sp_gaussian_noise","sp_additive_shade","sp_motion_blur","none"]
    augment_classes_weight: [0.2,0.2,0.2,0.2,0.2]
    augment_num: 4
    add_background: true

    brightness: 0.2
    contrast: 0.5
    saturation: 0.1
    hue: 0.0

    jpeg_low: 15
    jpeg_high: 75
    blur_range: [3,5]

    perturb: false
    perturb_max: 0

    sp_gaussian_range: [0,10]
    sp_speckle_prob_range: [0.0,0.0035]
    sp_nb_ellipse: 20
    sp_transparency_range: [-0.5,0.5]
    sp_kernel_size_range: [100,150]
    sp_max_kernel_size: 3
    resize_blur_min_ratio: 0.5