name: default_stage2

extractor: "NetworkShallowPool2"
embedder: "GREBilinearPoolPaddingDeepMore"

pretrain: true
pretrain_model_path: "data/model/default"
pretrain_step: -1
pretrain_extractor: true
pretrain_embedder: false

loss_type: "gefeats"
train_extractor: false
train_embedder: true

