sample_scale_begin: 0
sample_scale_inter: 0.5 # 0.70716
sample_scale_num: 5 # 6
sample_rotate_begin: -90
sample_rotate_inter: 45 # 30
sample_rotate_num: 5   # 7

hem_interval: 16

batch_size: 2
worker_num: 4

augmentation_args:
    h: 480
    w: 640

    test_harris: true
    harris_percentile: 99
    sample_num: 500

    augment: true
    augment_classes: ["none","jitter","sp_additive_shade","sp_motion_blur"]
    augment_classes_weight: [0.25, 0.25, 0.25, 0.25]
    augment_num: 1
    add_background: true

    brightness: 0.1
    contrast: 0.1
    saturation: 0.1
    hue: 0.0

    jpeg_low: 15
    jpeg_high: 75
    blur_range: [3,5]

    perturb: false
    perturb_max: 0

    sp_gaussian_range: [0,10]
    sp_speckle_prob_range: [0.0,0.0035]
    sp_nb_ellipse: 20
    sp_transparency_range: [-0.5,0.5]
    sp_kernel_size_range: [100,150]
    sp_max_kernel_size: 3
    resize_blur_min_ratio: 0.5
