name: eval # for evaluation only

extractor: "NetworkShallowPool2"
embedder: "GREBilinearPoolPaddingDeepMore"

pretrain: true
pretrain_model_path: "data/model/pretrain"
pretrain_step: -1
pretrain_extractor: true
pretrain_embedder: true

loss_type: "gefeats"
train_extractor: true
train_embedder: true

